### ISSUE TITLE
Implement char * myStrncat( char *dest, char *source, int n )

### ISSUE THREAD

**Issue by PGreatness** [PGreatness/MKS65C-Str#1]
This is the only one that needs to be done. The rest are working relatively well. We will work on myStrstr(char*, char) together afterwards.

**Comment by DevMMing** [comment]
I had a little trouble running the function as I want to print the char array i was changing but i neglected to remember how pointers work and I kept getting the combination of the two for the original and the new array. Other than that, there are no problems with my function.
